apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
        - name: springpetclinic
          image: nouurdevops/spring-petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
